strategies:  
  high_risk_long:  
    direction: long  
    leverage_rules:  
      type: volatility_based  
      max: 100  
      min: 40  
    entry_conditions:  
      - indicator: RSI  
        timeframe: 4h  
        operator: <  
        value: 35  
      - indicator: Volume  
        change: 1d  
        operator: >  
        value: 200%  
    exit_rules:  
      stop_loss:  
        type: trailing  
        activation: 5%  
        step: 1%  
      take_profit: 15%  
      emergency_triggers:  
        - liquidation_risk > 90%  
        - funding_rate < -0.1%  
        - system_health < 50%  
